---
- name: LetsEncrypt - Install EPEL
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
    state: present
  tags:
    - nginx
    - letsenrypt

- name: LetsEncrypt - Install Certbot for Nginx
  become: true
  ansible.builtin.yum:
    name:
      - certbot-nginx
    enablerepo: epel
    state: present
  tags:
    - nginx
    - letsenrypt

- name: LetsEncrypt - Check if certificates already exists.
  become: true
  ansible.builtin.stat:
    path: "{{ cert_path }}"
  register: certs
  tags:
    - nginx
    - letsenrypt

- name: LetsEncrypt - Generate cert
  become: true
  ansible.builtin.command: 'certbot --nginx {{ domains }} --non-interactive --agree-tos -m {{ email }}'
  when: not certs.stat.exists
  tags:
    - nginx
    - letsenrypt

- name: LetsEncrypt - Edit Crontab
  become: true
  ansible.builtin.cron:
    user: "root"
    name: "certbot autorenew"
    hour: "0"
    minute: "10"
    job: "/usr/bin/certbot renew --quiet"
    state: present
  tags:
    - nginx
    - letsenrypt
...
