---

- name: LetsEncrypt - Install EPEL
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
    state: latest
  tags: nginx

- name: LetsEncrypt - Install Certbot for Nginx
  become: true
  ansible.builtin.yum:
    name:
      - certbot-nginx
    enablerepo: epel
    state: latest
  tags: nginx

- name: LetsEncrypt - Check if certificates already exists.
  become: true
  ansible.builtin.stat:
    path: "{{ cert_path }}"
  register: certs
  tags: nginx

- name: LetsEncrypt - Generate cert
  become: true
  command: 'certbot --nginx {{ domains }} --test-cert --non-interactive --agree-tos -m {{ email }}'
  tags: nginx
  when: not certs.stat.exists

- name: LetsEncrypt - Edit Crontab 
  become: yes
  ansible.builtin.cron:
    user: "root"
    name: "certbot autorenew"
    hour: "0"
    minute: "10"
    job: "/usr/bin/certbot renew --quiet"
    state: present
  tags: nginx
