---

- name: Yum - Upgrade packages
  become: true
  ansible.builtin.yum:
    name: "*"
    enablerepo: base,updates,extras
    state: latest
    update_cache: yes
  tags:
    - nginx
    - yum

- name: Yum - Install packages
  become: true
  ansible.builtin.yum:
    name:
      - python36
    enablerepo: base,updates,extras
    state: latest
  tags:
    - nginx
    - yum

- name: Yum - Add Nginx Repo
  become: true
  ansible.builtin.template:
    src: nginx-stable.repo.j2
    dest: "{{ repo_path }}/nginx-stable.repo"
    mode: '644'
  tags:
    - nginx
    - yum

- name: Yum - Install Packages
  become: true
  yum:
    name:
      - nginx
    state: latest
  tags:
    - nginx
    - yum
